INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Szymon', 'Nowak', 0);
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Anna', 'Kowalska', 1);
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Jan', 'Wisniewski', 0);
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Agnieszka', 'Newska', 1);
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Zbigniew', 'Starzyk', 0);
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Wojciech', 'Regnos', 0);
INSERT INTO USER (FIRST_NAME, LAST_NAME, GENDER) VALUES ('Natalia', 'Zalabardo', 1);

INSERT INTO ADDRESS (CITY, STREET) VALUES ('Poznan', 'Mickiewicza');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Dublin', 'Dorset');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Warszawa', 'Armii Krajowej');
INSERT INTO ADDRESS (CITY, STREET) VALUES ('Krakow', 'Stradom');

INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (1, 2);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (2, 4);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (3, 3);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (4, 2);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (5, 3);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (6, 4);
INSERT INTO USER_ADDRESS (USER_ID, ADDRESS_ID) VALUES (7, 2);

INSERT INTO TODO (NAME, DESCRIPTION, STATUS) VALUES ('wyjsc z psem', 'Lorem ipsum', 'DONE');
INSERT INTO TODO (NAME, DESCRIPTION, STATUS) VALUES ('wyniesc smieci', 'Lorem ipsum', 'DONE');
INSERT INTO TODO (NAME, DESCRIPTION, STATUS) VALUES ('ugotowac obiad', 'Lorem ipsum', 'NEW');
INSERT INTO TODO (NAME, DESCRIPTION, STATUS) VALUES ('napisac cv', 'Lorem ipsum', 'IN_PROGRESS');